services.ts:2279 Error adding client: FirebaseError: Missing or insufficient permissions. addClient @ services.ts:2279 await in addClient handleSubmit @ Dashboard.tsx:3977 executeDispatch @ react-dom_client.js?v=0f6ef17f:13622 runWithFiberInDEV @ react-dom_client.js?v=0f6ef17f:997 processDispatchQueue @ react-dom_client.js?v=0f6ef17f:13658 (anonymous) @ react-dom_client.js?v=0f6ef17f:14071 batchedUpdates$1 @ react-dom_client.js?v=0f6ef17f:2626 dispatchEventForPluginEventSystem @ react-dom_client.js?v=0f6ef17f:13763 dispatchEvent @ react-dom_client.js?v=0f6ef17f:16784 dispatchDiscreteEvent @ react-dom_client.js?v=0f6ef17f:16765Understand this error Dashboard.tsx:4017 Error in handleSubmit: FirebaseError: Missing or insufficient permissions.